name: employee_ni_service
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  get_it: ^7.7.0
  animated_splash_screen: ^1.3.0
  dartz: ^0.10.1
  logger: ^2.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.2
  fl_chart: ^0.69.0
  intl: ^0.20.2
  toastification: ^2.3.0
  connectivity_plus: ^6.1.0
  signature: ^5.5.0
  uuid: ^4.5.1
  flutter_svg: ^2.0.16
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.12
  bloc_test: ^9.1.7
  mockito: ^5.4.5
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/png_image/nilogo.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/png_image/
    - assets/gif_image/
    - assets/jpg_image/
    - shorebird.yaml

